# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 031fe96b14183f632a04e81c826375c207805ef484588150f234cfb1c681eb0bf904e45ae3347897432c0b39cb475174084dc1403558e972aaff5a7461ee999d

test:
  secret_key_base: 6e552ad12f66b7f8aec46406d3ce0d9aef6db24a604c2d2fbf96b6b6f166ae3b823f67b3518171798d2f53970a92ada61d6afc569e4577246d5e8eefd32ff552

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
